# Generated by Django 5.0.4 on 2024-06-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRecords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='insert_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
