# Generated by Django 5.0.4 on 2024-06-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRecords', '0002_alter_bookrecord_insert_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='series_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
