# Generated by Django 5.0.4 on 2024-06-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRecords', '0003_alter_bookrecord_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
