# Generated by Django 5.0.4 on 2024-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRecords', '0004_alter_bookrecord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
