# Generated by Django 5.0.4 on 2024-06-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRecords', '0005_alter_bookrecord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='have',
            field=models.IntegerField(default=0),
        ),
    ]
