# Generated by Django 5.0.4 on 2024-07-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookRecords', '0008_alter_bookrecord_have'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
